#pragma once

#define CS_FIELD_NAME_MAX_LENGTH 24
#define CS_FIELD_NAME_MIN(a, b) (a) < (b) ? (a) : (b)

#define CS_FIELD_NAME_GET_CHAR(name, ii) ((CS_FIELD_NAME_MIN(ii, CS_FIELD_NAME_MAX_LENGTH)) < sizeof(name) / sizeof(*name) ? name[ii] : '\0')

#define CS_FIELD_NAME(s)\
	CS_FIELD_NAME_GET_CHAR(s, 0),\
	CS_FIELD_NAME_GET_CHAR(s, 1),\
	CS_FIELD_NAME_GET_CHAR(s, 2),\
	CS_FIELD_NAME_GET_CHAR(s, 3),\
	CS_FIELD_NAME_GET_CHAR(s, 4),\
	CS_FIELD_NAME_GET_CHAR(s, 5),\
	CS_FIELD_NAME_GET_CHAR(s, 6),\
	CS_FIELD_NAME_GET_CHAR(s, 7),\
	CS_FIELD_NAME_GET_CHAR(s, 8),\
	CS_FIELD_NAME_GET_CHAR(s, 9),\
	CS_FIELD_NAME_GET_CHAR(s, 10),\
	CS_FIELD_NAME_GET_CHAR(s, 11),\
	CS_FIELD_NAME_GET_CHAR(s, 12),\
	CS_FIELD_NAME_GET_CHAR(s, 13),\
	CS_FIELD_NAME_GET_CHAR(s, 14),\
	CS_FIELD_NAME_GET_CHAR(s, 15),\
	CS_FIELD_NAME_GET_CHAR(s, 16),\
	CS_FIELD_NAME_GET_CHAR(s, 17),\
	CS_FIELD_NAME_GET_CHAR(s, 18),\
	CS_FIELD_NAME_GET_CHAR(s, 19),\
	CS_FIELD_NAME_GET_CHAR(s, 20),\
	CS_FIELD_NAME_GET_CHAR(s, 21),\
	CS_FIELD_NAME_GET_CHAR(s, 22),\
	CS_FIELD_NAME_GET_CHAR(s, 23)

