#pragma once
#include "Macros.hpp"
#include "Types.hpp"
#include "BitFlags.hpp"
#include "Tuples.hpp"
#include "Singleton.hpp"
#include "StringUtils.hpp"
#include "Cast.hpp"
#include "TypeStrings.hpp"
